# Generated by Django 4.2.7 on 2025-12-03 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numeric_code', models.CharField(max_length=20, verbose_name='Código numérico')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de comisión')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'sellers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'active'], name='sellers_organiz_d95d53_idx'), models.Index(fields=['numeric_code'], name='sellers_numeric_ff8db5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.UniqueConstraint(fields=('organization', 'numeric_code'), name='unique_seller_code_per_org'),
        ),
    ]
