# Generated by Django 4.2.7 on 2025-12-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='branch',
        ),
    ]
