# Generated by Django 4.2.7 on 2025-12-04 01:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('products', models.ManyToManyField(blank=True, related_name='branches', to='products.product', verbose_name='Productos')),
                ('sellers', models.ManyToManyField(blank=True, related_name='branches', to='sellers.seller', verbose_name='Vendedores')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'active'], name='branches_organiz_bcd940_idx'), models.Index(fields=['code'], name='branches_code_95622b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_branch_code_per_org'),
        ),
    ]
