# Generated by Django 4.2.7 on 2025-12-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión que cobra este método de pago (0-100)', max_digits=5, verbose_name='Comisión (%)'),
        ),
    ]
