# Generated by Django 4.2.7 on 2025-12-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_products'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='products', to='branches.branch', verbose_name='Sucursales'),
        ),
    ]
